import os
DATABASE_URL = os.environ["DATABASE_URL"]
GMAPS_KEY = os.environ['GMAPS_KEY']
TWILIO_KEY_ACCOUNT_SID = os.environ['TWILIO_KEY_ACCOUNT_SID']
TWILIO_KEY_AUTH_TOKEN = os.environ['TWILIO_KEY_AUTH_TOKEN']
